version: 2

sources:
  - name: raw
    description: "Raw source data from DuckDB"
    schema: main
    tables:
      - name: issues
        description: "Issues data from the external system"
        columns:
          - name: description
            description: "The description of the issue, cleaned of special characters."
            tests:
              - not_null